### ISSUE TITLE
Reels are not working anymore 😢 

### ISSUE THREAD

**Issue by Guilamb** [Wikidepia/InstaFix#101]
Since the update in issue #96, it seems that reels are no longer being displayed. Additionally, attempting to use `/p` instead of `/reels` does not resolve the issue either.

This problem might be related to issue #95, but the symptoms are different as no image is being displayed in this case.
![image](https://github.com/Wikidepia/InstaFix/assets/18172904/98f1fc4e-c653-4982-be55-60fe62181ac0)

**Comment by Wikidepia** [comment]
This should be fixed after cache is expiring (3 days from now)
