### ISSUE TITLE
Telegram embeds not working

### ISSUE THREAD

**Issue by sallyFoster** [Wikidepia/InstaFix#104]
![image](https://github.com/Wikidepia/InstaFix/assets/104597302/91cb555d-d450-47ff-86cf-2ab383887fef)

**Comment by Wikidepia** [comment]
InstaFix only support IG.

**Comment by sallyFoster** [comment]
@Wikidepia The title of the repo says that it also supports telegram. You should get that changed then

**Comment by Wikidepia** [comment]
The description mentions InstaFix support fixing IG embeds in Discord and Telegram
