### ISSUE TITLE
ddinstagram.com not working for some posts and reels, redirects to instagram.com/p//p/

### ISSUE THREAD

**Issue by donmerendolo** [Wikidepia/InstaFix#107]
Hi, I found ddinstagram.com is not working for some posts. It says "Post might not be available".
In these posts I noticed that when opening the link, it redirects to the wrong url.

Example:
https://www.ddinstagram.com/p/C8Mjk1cILLh/
redirects to
https://www.instagram.com/p//p/C8Mjk1cILLh/?direct=true
when it should be
https://www.instagram.com/p/C8Mjk1cILLh/?direct=true

However I tried with this other post https://www.ddinstagram.com/p/C9aNNWvSySf/ and it points to the right url (well, it worked the first time I tried but not now).

Same for reels. In this case I couldn't find one that pointed to the right url and for almost all of the reels I tried, it said they were not available. I did find one reel whose embed worked (https://www.ddinstagram.com/reel/C9c4eQtRcn_/) but still when opening the link it pointed to an url with p//.

**Comment by Wikidepia** [comment]
Embed and redirect should be fixed. Please let me know if embed still failed

**Comment by donmerendolo** [comment]
Thank you!! The only thing I found is that in Telegram, reels sent from phone (Android at least) show just a small square with a thumbnail (and correctly in desktop):
![image](https://github.com/user-attachments/assets/78aed5e2-85c8-46e9-8adc-23e14bcbf28a)
But I don't know if that's expected. Pressing the small square plays the video anyways.

**Comment by patrickwelker** [comment]
I don’t know if I should revive the issue, but this reel link doesn’t work either: https://www.ddinstagram.com/reel/C_ePR8mPjKA/

**Comment by mulano1977** [comment]
all links via ddinstagram no longer work. 500 internal error from website
