### ISSUE TITLE
Can’t specify which image in a carousel post to embed anymore

### ISSUE THREAD

**Issue by superrpotion** [Wikidepia/InstaFix#108]
Hi, just noticed this issue recently: 

Before, if you had a link to a carousel post like these:
https://www.ddinstagram.com/p/C9P6O6lpQsi/
(images only) 
https://www.ddinstagram.com/p/C8NHJMVOhzk/
(Video + images) 
And you could add `/1` or `/2`to the end of the link to only show that slide in the embed. 
For example: 
`https://www.ddinstagram.com/p/C9P6O6lpQsi/2` 
to only show the second slide in the embed 

Now, adding a /1 or /2 will do nothing, and the embed will show every single image slide instead of the one you specified.

**Comment by Wikidepia** [comment]
This should be fixed now, please let me know if it is still broken
