### ISSUE TITLE
Embed not showing correctly

### ISSUE THREAD

**Issue by JessicaThorst** [Wikidepia/InstaFix#109]
ddinstagram embedding is only showing the same thing for every link being sent, it reads as follows:
InstaFix
Post might not be available 

Image example ![InstaFix Post might not be available](https://github.com/user-attachments/assets/d9990f6e-5189-47fd-979e-265e50185d18)

**Comment by fowler36** [comment]
the same happening on Telegram lately

**Comment by Wikidepia** [comment]
Do you have any example?

**Comment by fowler36** [comment]
it's a private Telegram channel

**Comment by Wikidepia** [comment]
It should not happen anymore, there might be something wrong with some other post. You can just send me the IG post links

![mit](https://github.com/user-attachments/assets/65b8c06d-6e11-4e68-8e7f-45d95ba9cf99)
