### ISSUE TITLE
Question about cookies

### ISSUE THREAD

**Issue by htkg** [Wikidepia/InstaFix#114]
This is a question not an issue. How does this work without cookies?

I'm developing almost the same thing, but for downloading videos/pictures for my friends.
My solution only works with cookies.

Instagram anonymous browsing was available just a few months ago, but it doesn't work now
`{'message': 'Please wait a few minutes before you try again.', 'require_login': True, 'status': 'fail'}`

**Comment by Wikidepia** [comment]
Hello, I scrape IG data using residential IP like LTE from a phone
