### ISSUE TITLE
Captions don't appear in the embed anymore

### ISSUE THREAD

**Issue by Apocolypto** [Wikidepia/InstaFix#115]
When embedding a reel on Discord, it only shows the poster's username when there used to be a caption and the username included.

![OCh0gWFy](https://github.com/user-attachments/assets/5df303af-5b75-40d9-9f49-e0ac7e07999d)

**Comment by Wikidepia** [comment]
Can you try it again? It should be fixed

**Comment by Apocolypto** [comment]
it appears to be fixed, thanks!
