### ISSUE TITLE
How to set several type of embed?

### ISSUE THREAD

**Issue by pc-v2** [Wikidepia/InstaFix#116]
I'am currently run this on my server. but can't seem working with g.domain and d.mydomain

**Comment by Wikidepia** [comment]
If you use Caddy you can use the following config: https://github.com/Wikidepia/InstaFix/blob/main/Caddyfile

**Comment by pc-v2** [comment]
I am using docker to deploy it without traefik

**Comment by Wikidepia** [comment]
You need to use some sort of reverse proxy that can rewrite the url, you can use caddy or nginx

**Comment by pc-v2** [comment]
it's working now but reels or any video can't be scrapped, I will make new issue
