### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by seriaati** [Wikidepia/InstaFix#123]
![image](https://github.com/user-attachments/assets/ad83c77c-3a41-4a7d-addc-3e498affe2c9)

**Comment by kopyl** [comment]
Yeah, something is wrong with my link as well

https://ddinstagram.com/reel/DABgr5ttlKs

**Comment by Wikidepia** [comment]
Should be back online now.

**Comment by Wikidepia** [comment]
Oops I guess not sorry

**Comment by Wikidepia** [comment]
Should be back for real this time. Apparently IG have a new post id that starts with 'D' not just 'C'.
