### ISSUE TITLE
d.dd inconsistency

### ISSUE THREAD

**Issue by yuvlian** [Wikidepia/InstaFix#131]
Link 1: https://d.ddinstagram.com/reel/C-ZutOAIA0z/
![image](https://github.com/user-attachments/assets/4dbe0098-fe53-4584-8f28-22df0069a8af)

Link 2: https://d.ddinstagram.com/reel/DBJbQueIfqK/
![image](https://github.com/user-attachments/assets/a7ceb94e-e116-4d06-89f3-71fa1644e2aa)

Link 3: https://d.ddinstagram.com/reel/C_LXTpMuNaj/
![image](https://github.com/user-attachments/assets/6d6b2d44-1bc0-411d-b639-b29ae40f6c1e)

**Comment by kpopdev** [comment]
@Wikidepia The ddinstagram is down it shows login to show the pictures. the embed on discord is dead.

**Comment by GeorgeWL** [comment]
> @Wikidepia The ddinstagram is down it shows login to show the pictures. the embed on discord is dead.

That's fully unrelated to this issue. 

Please report as a new issue rather than as a reply to something entirely unrelated

**Comment by GeorgeWL** [comment]
Anyhow, just started seeing this today as well, screenshot and example link
![Screenshot_2024-10-29-21-14-19-23_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/user-attachments/assets/3ac7163d-485b-4d3d-8082-192a1664ff52)

https://d.ddinstagram.com/p/DBrCZvmR7IQ/?igsh=MzZ4ZGp1MjIxZ3J5

**Comment by alan1420** [comment]
It seems like the reverse proxy (Caddy) didn't redirect the d and g subdomain. For now you have to use ?direct=true or ?gallery=true with the root domain. Example:
https://www.ddinstagram.com/reel/DBJbQueIfqK/?gallery=true

**Comment by Wikidepia** [comment]
This should be fixed now, can you try it?

**Comment by alan1420** [comment]
It is, thanks!
