### ISSUE TITLE
Why does ddinstagram not work sometimes?

### ISSUE THREAD

**Issue by seriaati** [Wikidepia/InstaFix#136]
First of all, thanks for creating this tool, it certainly is very helpful.
However, it seems that the service is very unstable/not reliable recently, is there a reason to that (e.g. being rate limited by Meta)?
Because I am wondering if self-hosting will fix the unreliability.

**Comment by shortazn97** [comment]
Ditto. It's been acting up. Maybe an API issue. Sometimes the embed just says something about needing to log in. other times there's no embed at all

**Comment by fkoemep** [comment]
Here's an example which doesn't work, no preview, no embed, nothing

https://www.instagram.com/p/DCy7Cs_uBhl

I tried the following ways but nothing worked:

- https://www.ddinstagram.com/p/DCy7Cs_uBhl
- https://www.ddinstagram.com/reel/DCy7Cs_uBhl
- https://d.ddinstagram.com/p/DCy7Cs_uBhl
- https://d.ddinstagram.com/reel/DCy7Cs_uBhl

**Comment by Wikidepia** [comment]
It should be back now, remote scraper have some issue

**Comment by fkoemep** [comment]
Still not working for me :(

**Comment by seriaati** [comment]
So it has nothing to do with rate limits?
