### ISSUE TITLE
Telegram issue

### ISSUE THREAD

**Issue by Kirurusha** [Wikidepia/InstaFix#138]
Hello. I wanted to bring to your attention that your application seems to struggle with processing a large number of videos. This issue might be related to regional settings or possibly other factors. Could you please take a look into this? The problem specifically pertains to links shared on Telegram. 

Thanks

**Comment by Kirurusha** [comment]
![image](https://github.com/user-attachments/assets/dab2607a-4567-495d-9300-66cf5e7629cd)

**Comment by Kirurusha** [comment]
![image](https://github.com/user-attachments/assets/790fb916-5e74-4811-96f5-65c97a84acff)

**Comment by Wikidepia** [comment]
There is a problem with InstaFix at that time, it should be fixed now. Can you try with a different post?
