### ISSUE TITLE
hey ddinstagram isnt working anymore on discord

### ISSUE THREAD

**Issue by deadpoolstark** [Wikidepia/InstaFix#141]
![2](https://github.com/user-attachments/assets/cc4be6e0-78ab-42cb-9b03-43bbd909cceb)
its broken. anything we are doing wrong..? or what??

**Comment by kpopdev** [comment]
@Wikidepia im sure its dead, it wont show anything.

**Comment by TheCheekiBreekiest** [comment]
Dead for at least a week now
