### ISSUE TITLE
Add ability to remove or shorten post content from embeds

### ISSUE THREAD

**Issue by Feng94** [Wikidepia/InstaFix#15]
I love this tool and have been using it a lot!

Just a suggestion, perhaps somehow having some sort of setting to remove the embed text from the embed would be great to keep links clean. Especially when they are full of useless hashtags.

Or a setting to greatly shorten it to a one line thing.

For example:
![image](https://user-images.githubusercontent.com/8751189/235288988-2e8eeab2-2d4e-4917-ac0f-86d8939b0ea3.png)
Removing the crossed out bit.

Given that the ease of use comes from simply adding `dd` to the url, perhaps may have to set up a separate server for this capability while keeping it easy to prepend the url.

**Comment by GeorgeWL** [comment]
Yeah I'd like this too tbh, like, this post has 25 lines of just

```
-
```

**Comment by Soitora** [comment]
Yeah the description of posts is a downside and came here to see if there was another url that didn't include it

**Comment by josephisticated** [comment]
for photos you can go with https://www.ddinstagram.com/**grid**/something instead of https://www.ddinstagram.com/**p**/something but don't know what to do with reels. Would really appreciate if this was a thing.

**Comment by Feng94** [comment]
use d.dd instead of dd to only embed media!

**Comment by GeorgeWL** [comment]
👑 thanks for addign that feature

**Comment by jirafey** [comment]
does it work ?
https://www.ddinstagram.com/p/CcAr7QOF3EQ/
https://www.d.ddinstagram.com/p/CcAr7QOF3EQ/
![image](https://github.com/user-attachments/assets/063eea00-ba11-42e2-b5be-51329908541f)

**Comment by Feng94** [comment]
> does it work ? https://www.ddinstagram.com/p/CcAr7QOF3EQ/ https://www.d.ddinstagram.com/p/CcAr7QOF3EQ/ ![image](https://private-user-images.githubusercontent.com/97115044/353550501-063eea00-ba11-42e2-b5be-51329908541f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTA4MzYsIm5iZiI6MTcyMjM5MDUzNiwicGF0aCI6Ii85NzExNTA0NC8zNTM1NTA1MDEtMDYzZWVhMDAtYmExMS00MmUyLWI1YmUtNTEzMjk5MDg1NDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAxNDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MTM0MmNhZDZlZWRkNWUxYmQwNWNmYjNmZTJjYjk0YWNlNjQyZmU1NWY3YWY2NmM0M2IyNzc5ZjdjYWEwYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vcA3fnLUHOyw-KtG_YFartL-KSzblWy12VfC5q7Sxfs)

you must change the url of https://www.d.ddinstagram.com/p/CcAr7QOF3EQ/ to https://d.ddinstagram.com/p/CcAr7QOF3EQ/

**Comment by Feng94** [comment]
oops i accidentally closed it
