### ISSUE TITLE
Request for fxinstagram.com as well!

### ISSUE THREAD

**Issue by BlinksTale** [Wikidepia/InstaFix#17]
Feature request: since fxtwitter is well known and fxinstagram is available to buy, it would be great to have a consistent url design language here.

Great work though!

**Comment by buxy-xyz** [comment]
true, but dd is faster to type than fx.

> Feature request: since fxtwitter is well known and fxinstagram is available to buy, it would be great to have a consistent url design language here.
> 
> Great work though!

**Comment by mikaelg79** [comment]
Unfortunately someone is squatting the fxinstagram.com domain.

**Comment by favna** [comment]
I mean at that rate you may as well get fixtagram

**Comment by Wikidepia** [comment]
Its already registered, not for now
