### ISSUE TITLE
Support for Instagram stories?

### ISSUE THREAD

**Issue by PrivatePP** [Wikidepia/InstaFix#19]
As of now, IG stories embed through Instafix only display the thumbnail, not the video.

Example link
https://www.ddinstagram.com/stories/user/0000000000000/

**Comment by Wikidepia** [comment]
It's unlikely that video stories will be supported in the near future, since accessing stories without an account is not possible.

**Comment by Andrew-J-Larson** [comment]
> It's unlikely that video stories will be supported in the near future, since accessing stories without an account is not possible.
> 
> 

Maybe there should be a disclaimer about this somewhere on the GitHub read me, and also on the website detailing the service.
