### ISSUE TITLE
Embedded content will not load

### ISSUE THREAD

**Issue by craftio** [Wikidepia/InstaFix#22]
Good day!

I have found that lately a lot if not all of the instagram posts & reels I try to embed via ddinstagram do have the building blocks for embedded content like the title & hashtags etc. but the actual media is not there.

I have an example added here below:
![image](https://github.com/Wikidepia/InstaFix/assets/12518794/f1712bb9-7fa8-4678-ac6e-e255012a9469)

I hope to see it fixed and do wish to know if the issue is seen.

Greetings,

- Craft

**Comment by Wikidepia** [comment]
Should be fixed now
