### ISSUE TITLE
Wrong redirect with instagram story

### ISSUE THREAD

**Issue by huskyon9** [Wikidepia/InstaFix#27]
When user copy the story link and add the "dd" in the story link it will redirect to a fixed link 

"https://www.instagram.com/p/Cu7DuXWsIj5/"

this instagram post link was deleted, the preview function is works fine, only the redirect have issue.

Please have a look for this issue. Thank you for your work on this project.

**Comment by Wikidepia** [comment]
Thanks, I forgot to do that

**Comment by huskyon9** [comment]
Thank you :)
