### ISSUE TITLE
Doesn't work with reels (only posts)

### ISSUE THREAD

**Issue by styfeng** [Wikidepia/InstaFix#3]
Seems to only work for posts (e.g. [here](https://www.instagram.com/tv/Cgm_LR_pYVI/?utm_source=ig_web_copy_link)) and not reels (e.g. [here](https://www.instagram.com/p/CjMsn_BAtmf/)). With reels, the embed portion loads for a long time on discord until it eventually fails.

**Comment by Wikidepia** [comment]
Thank you for providing this information!

Instagram's video speed is sometimes limited, causing the discord crawler to timeout. I intend to add a proxy because this only occurs in the browser and not with wget or another downloader.

**Comment by Wikidepia** [comment]
It should work now
