### ISSUE TITLE
 The Home page is not according to the app demo

### ISSUE THREAD

**Issue by NZ62AN** [Wikidepia/InstaFix#30]
![local](https://github.com/Wikidepia/InstaFix/assets/42322285/7fd3651f-f5d0-495f-8c19-70508019f762)

Hello, I ran the program successfully , but when I post the local address http://127.0.0.1:8080/ for example, p/CwdV203ocVB/, the address is like this http://127.0.0.1:8080/p/CwdV203ocVB/ but after It takes a few moments to redirect to the same post on Instagram and there is no save option so I can download it. What is the problem?
![redirect](https://github.com/Wikidepia/InstaFix/assets/42322285/1f9fc055-3b9c-46e1-8969-108e5abae203)

The home page is not according to the app demo, where we can edit the post address and...

**Comment by Wikidepia** [comment]
Thanks @almi05 for answering, I will close this issue
