### ISSUE TITLE
Currently Inoperable on Discord

### ISSUE THREAD

**Issue by KitPlays** [Wikidepia/InstaFix#31]
Purely a layman who enjoys utilizing this fix on Discord. Several of the folks in servers noticing previews not loading today. So just flagging!

![Screenshot_20230906_201935_Discord](https://github.com/Wikidepia/InstaFix/assets/144292552/36da6dfa-da06-489e-9447-d29bd3ef2312)

**Comment by Wikidepia** [comment]
I've cleared cache please try again it should work now
