### ISSUE TITLE
Is the number of requests for each IP limited?

### ISSUE THREAD

**Issue by Anishtang** [Wikidepia/InstaFix#32]
Today, no file can be attached to Telegram for my IP. This is despite the fact that there is no problem with another mobile phone that I have and attach  is done.

What should I do to remove this limitation?

**Comment by Anishtang** [comment]
Is there anyone who has faced this problem?

**Comment by Wikidepia** [comment]
There should not be any limit, dunno why that happen :/

**Comment by abhaytomar05** [comment]
> Is there anyone who has faced this problem?

Yup it's with me tooo
