### ISSUE TITLE
Reel video/Video post won't embed on discord

### ISSUE THREAD

**Issue by moshsh** [Wikidepia/InstaFix#33]
https://www.ddinstagram.com/p/CwKXLaqs126/

https://www.ddinstagram.com/reel/CwKXLaqs126/

Neither link embeds a video on discord, they embed 1 frame of the video as an image,  just wondering if this is a bug or only certain instagram videos will embed when using instafix

**Comment by Wikidepia** [comment]
Sometimes certain reels is limited to image only, there is no fix for that.
