### ISSUE TITLE
False positive on post unavailable

### ISSUE THREAD

**Issue by x0rld** [Wikidepia/InstaFix#34]
When i try on this reel i have in the embed a message telling me it's not available but i can open it
https://www.instagram.com/reel/CxbCygXoxzv/

**Comment by Wikidepia** [comment]
It seems that reel is posted by restricted profile (18+), instafix cant access it

**Comment by x0rld** [comment]
hi @Wikidepia, how do you check if it's restricted ? cause if have this one too now https://www.instagram.com/p/Cx5J7uyL6f6/
