### ISSUE TITLE
Japanese text becomes mojibake when passed through ddinstagram

### ISSUE THREAD

**Issue by cooljeanius** [Wikidepia/InstaFix#38]
https://www.ddinstagram.com/reel/CyAxVyzx3GV/

Comes through looking like this:
<img width="861" alt="Screen Shot 2023-10-21 at 00 37 01" src="https://github.com/Wikidepia/InstaFix/assets/1388660/8ce3fdc6-a40e-401f-b966-3cbe3419691e">

**Comment by Wikidepia** [comment]
This should be fixed, can you try with another post?

**Comment by cooljeanius** [comment]
I don't actually use Instagram myself, I only see the links that other people post to it in Discord, so I don't have any other posts available to test, unfortunately... this is the only link I've seen it happen with... Although, I don't see how it can be fixed, though, seeing as the latest commit was 2 weeks ago, and I saw this just yesterday?

**Comment by cooljeanius** [comment]
In which commit was this completed?

**Comment by Wikidepia** [comment]
https://github.com/Wikidepia/InstaFix-Go/commit/6152b135e466edfe28156d40ecb0b3ee07d15a57

**Comment by cooljeanius** [comment]
> [Wikidepia/InstaFix-Go@6152b13](https://github.com/Wikidepia/InstaFix-Go/commit/6152b135e466edfe28156d40ecb0b3ee07d15a57)

Ah, I didn't realize the repo had changed! Thanks.
