### ISSUE TITLE
Gifs are converting to jpgs

### ISSUE THREAD

**Issue by YJB-Gay** [Wikidepia/InstaFix#39]
https://www.ddinstagram.com/reel/Cy6xB5MNaNu/ converted to a jpg file when the original post has a gif file

**Comment by Wikidepia** [comment]
Sometimes reels is blocked by Instagram to be viewed via embed, there are bypasses but it will cost $$$ and time.

https://www.instagram.com/reel/Cy6xB5MNaNu/embed/captioned (blocked "Watch on Instagram")
