### ISSUE TITLE
Links to Instagram Stories fail to generate embeds, despite using the correct URL format

### ISSUE THREAD

**Issue by SuperSajuuk** [Wikidepia/InstaFix#42]
Hi. I've been using this url fixer for a while since Instagram regularly breaks embeds or shows a log-in embed.

However, I've noticed that, despite stories URL's being supported by ddinstagram.com [according to the code], the embed doesn't generate for them, even though they are valid story URLs and in the format suggested by the code. Manually navigating to a "fixed" story url shows `Cannot GET /stories/usernamehere/storyid` from ddinstagram.com

Any idea if this can be fixed?

**Comment by Wikidepia** [comment]
Should be fixed https://github.com/Wikidepia/InstaFix/commit/9433db869bb1e0c708009f2354af0e3bcb4814ad. It will only show images as video is not supported at this time.

**Comment by SuperSajuuk** [comment]
> Should be fixed [9433db8](https://github.com/Wikidepia/InstaFix/commit/9433db869bb1e0c708009f2354af0e3bcb4814ad). It will only show images as video is not supported at this time.

Can confirm fixed. Hopefully embedding the video will be supported soon! 👍
