### ISSUE TITLE
Request to add support for `/?img_index=2` to embed collage content

### ISSUE THREAD

**Issue by O1yyy** [Wikidepia/InstaFix#44]
works flawlessly, thank you for the awesome project!

i'd like to suggest a feature for better support towards collage posts, where currently if you try to embed a link such as:
`https://www.ddinstagram.com/p/CzDW7bqSo5t/?img_index=2`
the link doesnt embed, but the url states the argument for the correct video
could it be possible to integrate support for these types of links?

it also appears that trying to embed the collage without the argument fails to embed the first video at all, so i'm just noting the behavior down in case there could be a potential fix
`https://www.ddinstagram.com/p/CzDW7bqSo5t/`

**Comment by Mf3434** [comment]
> works flawlessly, thank you for the awesome project!
> 
> 
> 
> i'd like to suggest a feature for better support towards collage posts, where currently if you try to embed a link such as:
> 
> `https://www.ddinstagram.com/p/CzDW7bqSo5t/?img_index=2`
> 
> the link doesnt embed, but the url states the argument for the correct video
> 
> could it be possible to integrate support for these types of links?
> 
> 
> 
> it also appears that trying to embed the collage without the argument fails to embed the first video at all, so i'm just noting the behavior down in case there could be a potential fix
> 
> `https://www.ddinstagram.com/p/CzDW7bqSo5t/`

**Comment by Wikidepia** [comment]
Fixed
