### ISSUE TITLE
[BUG] Weird clip behaviour

### ISSUE THREAD

**Issue by Ceddicedced** [Wikidepia/InstaFix#50]
![image](https://github.com/Wikidepia/InstaFix/assets/19432359/ea467791-ded1-4b5c-b859-2720fada34da)

I have a problem with the first and third link send. These are clips and are getting redirected perfectly fine. But it seems that the preview is not working right. The strange thing is that if i use the original instagram link, then there is a preview which is working. 

![image](https://github.com/Wikidepia/InstaFix/assets/19432359/dfa9615d-bfc7-48ce-b57e-f75608c66705)

https://www.instagram.com/p/CztUBHURuf5/

https://ddinstagram.com/p/C0UNPgMqT4y/
https://ddinstagram.com/p/CztUBHURuf5/

**Comment by Wikidepia** [comment]
Should be fixed in https://github.com/Wikidepia/InstaFix/commit/74163f66131e8597891b9954a91449e8325fe709, thanks for the report!
