### ISSUE TITLE
Video not embedded

### ISSUE THREAD

**Issue by UlyssesZh** [Wikidepia/InstaFix#51]
https://www.ddinstagram.com/p/C0SMvQpAoBg/

**Comment by Wikidepia** [comment]
Embed just fine in telegram, where did you try it?

**Comment by UlyssesZh** [comment]
I tried on Discord. I tried just now, and it did not work.
After you said it works on Telegram, I also tested it on Telegram, and it worked. Seems strange.

**Comment by Wikidepia** [comment]
Should be fixed in 74163f66131e8597891b9954a91449e8325fe709, thanks for the report!
