### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by d-Rickyy-b** [Wikidepia/InstaFix#52]
Hi there, thanks for your work. I was wondering how this project's code is licensed? You did not put a LICENSE file in your repo so it's hard for people to figure out if and how this code can be legally (re-)used.

**Comment by x0rld** [comment]
https://github.com/Wikidepia/InstaFix/commit/4824ceeffb25d3ec55fcaed97b34cdf324fccc00 
it has been adeed last week after your issue probably @d-Rickyy-b

**Comment by d-Rickyy-b** [comment]
Oh lovely, thank you @x0rld and @Wikidepia :)
