### ISSUE TITLE
Reel showing images in stead of videos

### ISSUE THREAD

**Issue by reddere** [Wikidepia/InstaFix#53]
take this reel as an example: https://www.instagram.com/reel/C0cntOzx3Ak/
the links becomes: https://www.ddinstagram.com/reel/C0cntOzx3Ak/

it gets shown as an image, instead of a video.
![immagine](https://github.com/Wikidepia/InstaFix/assets/111050360/54794136-b85d-42a4-9a50-22a05937433f)

Can you fix that?

**Comment by Wikidepia** [comment]
This is known issue, https://github.com/Wikidepia/InstaFix/issues/39#issuecomment-1786686806. I dont have plans to fix it right now
