### ISSUE TITLE
sometimes only photo or post text of video 

### ISSUE THREAD

**Issue by yukari-takeba** [Wikidepia/InstaFix#56]
I am using instafix for 1 week and I think reason with this problem is account itself . I just send myself 80 links(dd) and 72 links perfectly fine but 8 is problem . I just want to understand what problem is and I think I figured out . 

for example I tried to download this "https://www.instagram.com/reel/C09k0z5vRG3/" and failed . only post text is showing up in telegram . if you go to post account ("https://www.instagram.com/suzanramic/") all video links are not working . every video link with dd is same ... only post text I can see , like this . 
![Ekran Görüntüsü (28)](https://github.com/Wikidepia/InstaFix/assets/99480811/3e9006eb-036a-4264-8af9-353b2f22f3b5)

**Comment by kevosmin** [comment]
I’m having the same issue

**Comment by Wikidepia** [comment]
Sometimes when video size is bigger than 20MB, Telegram refuses to embed it, https://www.instagram.com/reel/C09k0z5vRG3/ have 20.3MB video size
