### ISSUE TITLE
Embeds stopped working?

### ISSUE THREAD

**Issue by kjchrz03** [Wikidepia/InstaFix#57]
I was able to post in my discord server an Instagram Post with the leading dd on 12/19 and it successfully displayed. Today, 12/20 I posted around 10pm and no links display. Was there a change?

**Comment by Wikidepia** [comment]
Yeah, the server have used all the available bandwidth, I will ask the server provider to hopefully reset it

**Comment by Wikidepia** [comment]
It should work now
