### ISSUE TITLE
Some videos only embed static thumbnail

### ISSUE THREAD

**Issue by Ngame989** [Wikidepia/InstaFix#6]
I'm not 100% sure if this is tied to reels vs posts, I haven't found any true consistency between ones that work and ones that don't. A lot of videos only load the preview image and don't load a video player at all (e.g. [here](https://www.ddinstagram.com/p/Cj7qwltNf4U/)). I've found the most consistent success with videos with multiple images/videos where the first upload is a video and there's at least one static image included in the post (e.g. [here](https://www.ddinstagram.com/p/CjsTshAJhhv/)). [This](https://www.ddinstagram.com/p/Cj1PqL-gecW/) one worked when I first posted it in a Discord server a few days ago (and the poster's comment specifies it was uploaded as a post, not a reel), but now that embed's video player freezes at 0:00 and posting it in another server just loads the static thumbnail instead.

**Comment by Wikidepia** [comment]
Hello, that is one of the limitations of scraping Instagram Embed, because IG sometimes restricts and only shows the thumbnail.
