### ISSUE TITLE
im sure the proxy website is down.

### ISSUE THREAD

**Issue by kpopdev** [Wikidepia/InstaFix#62]
https://envoy.lol/ the proxy website is down

**Comment by kjchrz03** [comment]
Yes that would seem to be the case, although I am getting partial embeds right now 

![image](https://github.com/Wikidepia/InstaFix/assets/98568686/2d893f53-b1f8-4f0c-8e12-44dfcfcbb03b)

**Comment by Wikidepia** [comment]
Thanks for the report, I will check it now

**Comment by Wikidepia** [comment]
This should be fixed, caddy for some reason crashed and does not come back again :/

**Comment by kpopdev** [comment]
the ddinstagram is down again it wont embed anything. 
![image](https://github.com/Wikidepia/InstaFix/assets/28566705/47aa145d-0a4b-44fc-9f89-bfc3875c5194)

**Comment by kpopdev** [comment]
@Wikidepia ^^
