### ISSUE TITLE
URLs paths that are prefixed with the username do not work

### ISSUE THREAD

**Issue by Scrxtchy** [Wikidepia/InstaFix#64]
I don't know how well known or how often they show up, but instafix doesn't like them (404)
https://www.instagram.com/instagram/p/C2KzJvNRzSF/

![image](https://github.com/Wikidepia/InstaFix/assets/12771982/9bea0594-7824-4ffb-b36e-c66c8facd3f1)
![image](https://github.com/Wikidepia/InstaFix/assets/12771982/b3f49fde-25b0-4caa-9840-d2a367c9358e)

had to look at the code to see why these weren't working as it assumes that the path shouldn't include these

**Comment by Wikidepia** [comment]
That is a new URL, I will add it later
Thanks for the report

**Comment by Wikidepia** [comment]
This should work now, please reopen if not
