### ISSUE TITLE
Links aren’t working anymore 

### ISSUE THREAD

**Issue by kevosmin** [Wikidepia/InstaFix#7]
I’ve tired several links and none of them seem to be embedded anymore when adding dd in the links 
![803DA3FE-816C-49C0-9924-7083D92BF790](https://user-images.githubusercontent.com/36827792/208496914-7ad0d90b-e1d7-4715-8be9-4eb95dca9d16[Screen recording of it](https://imgur.com/a/TSnYkuI) .jpeg)

**Comment by kevosmin** [comment]
I think it stopped working again 😭 I’m not too sure, I’ll post a screen recording [Here’s the screen recording ](https://imgur.com/a/CNVOzAn)

**Comment by Wikidepia** [comment]
Hi, I've already rolled out a new fix. Could you please try a different link?

**Comment by kevosmin** [comment]
It seems to working again, even with the same links I’ve tried before. Thank you! I’ll let you know if face an issues in the future
