### ISSUE TITLE
How to download instagram stories by ddinstagram or instafix?

### ISSUE THREAD

**Issue by agh620** [Wikidepia/InstaFix#70]
I tried to download stories using ddinstagram or instafix from discord but it only download image of story and can't download in mp4 format!  
for example I tried a story url similar to following:  
**https://www.ddinstagram.com/stories/username/*******************/**
and it shows me following with a image embed:  
**https://www.ddinstagram.com/images/[shortcode]/1**  
  
I even tried with video url but it still show me image of stories!  
**https://www.ddinstagram.com/videos/[shortcode]/1**  
  
How to fix this?

**Comment by Wikidepia** [comment]
It will not be supported any time soon as long as it is impossible to get stories without an account

**Comment by agh620** [comment]
One of my friends claims that through an Instagram vulnerability, stories can be downloaded without cookies or logging into the account.  
I couldn't find it and my friend never share with me!

**Comment by agh620** [comment]
If I login to an account then How can I remove instagram story download limit? I want to use story download api without limit of my account.

**Comment by Wikidepia** [comment]
I do not know, please find it yourself.
