### ISSUE TITLE
Automatically ignore query string

### ISSUE THREAD

**Issue by UlyssesZh** [Wikidepia/InstaFix#75]
For example, `https://www.ddinstagram.com/reel/C2dcK_wxCd4/?igsh=MTFkNjc3NGt6czVrNw==` does not show embed properly on Discord; removing the query string makes it work.

**Comment by Wikidepia** [comment]
InstaFix should ignore query string already, only `img_index` is used, it might be discord problem. Please reopen if issue still exist.
