### ISSUE TITLE
A self-hosted version of the service doesn't process video properly

### ISSUE THREAD

**Issue by ghost** [Wikidepia/InstaFix#78]
I deployed own instance of the service. And I tested it on link https://instagram.com/p/C20PQNvvHR7/
That link works fine for the public instance `ddinstagram`
![изображение](https://github.com/Wikidepia/InstaFix/assets/5565035/f381febf-1992-4f3d-9ae1-83ad318f2691)
But doesn't work for my instance.
Self-hosted service behind Nginx:
![изображение](https://github.com/Wikidepia/InstaFix/assets/5565035/b77b2929-5a90-4fd4-8c1f-610bb7510531)
Same directly:
![изображение](https://github.com/Wikidepia/InstaFix/assets/5565035/88cb5393-11cd-4720-ad35-9552ed86eb9d)

**Comment by Wikidepia** [comment]
Your server IP might be blocked, InstaFix cant bypass that except using remote scraper (https://github.com/Wikidepia/InstaFix-remote-scraper) with residential IP or using residential proxies.
