### ISSUE TITLE
Instagram posts with slides

### ISSUE THREAD

**Issue by josephisticated** [Wikidepia/InstaFix#8]
How do I post an embed that shows the slides other than the first?

**Comment by Wikidepia** [comment]
Hi, I dont get it. do you have any example?

**Comment by josephisticated** [comment]
![image](https://user-images.githubusercontent.com/53388005/210250610-fc584967-d256-4c16-8724-12b40bc703b0.png)
i mean like when there are multiple pictures on a single post, what do we do? vxtwitter has c.vxtwitter.com, it combines all the images in the post into a single image and you can add /1, /2 etc. to show a single image in that post

**Comment by josephisticated** [comment]
oh and some videos embeds as pictures on discord, dont know why

**Comment by Wikidepia** [comment]
> ![image](https://user-images.githubusercontent.com/53388005/210250610-fc584967-d256-4c16-8724-12b40bc703b0.png) i mean like when there are multiple pictures on a single post, what do we do? vxtwitter has c.vxtwitter.com, it combines all the images in the post into a single image and you can add /1, /2 etc. to show a single image in that post

InstaFix merges images as default and you can add /1, /2 to get a single image
