### ISSUE TITLE
Gallery View

### ISSUE THREAD

**Issue by barraIhsan** [Wikidepia/InstaFix#85]
Just like #37, but instead it only show the author and the media itself (minimal embed), just like [FxTwitter did](https://github.com/FixTweet/FxTwitter?tab=readme-ov-file#gallery-view)
so `g.ddinstagram.com`

**Comment by Wikidepia** [comment]
Thats a great idea, I will try to implement it :)

**Comment by Wikidepia** [comment]
It should work now (https://github.com/Wikidepia/InstaFix/commit/20af16fbdb8b9d4132a6505ccfc46b17a661851b)
