### ISSUE TITLE
How to embed just a single image?

### ISSUE THREAD

**Issue by jhmejia** [Wikidepia/InstaFix#86]
Was wondering how to embed a single image out of a gallery, ie, just image 1.

What I see:
![image](https://github.com/Wikidepia/InstaFix/assets/29128358/e82a87fe-f79c-4a7b-b1ab-784e28b496fe)

What I want: just the first image (![image](https://github.com/Wikidepia/InstaFix/assets/29128358/28aa80f6-c7fd-4ea9-819c-c59ad2a43569))

Thank you!

**Comment by Wikidepia** [comment]
You need to add `/1` before the question mark (`?igsh...`) in the URL. For example: https://www.ddinstagram.com/p/C5e2YQRJVd-/1
