### ISSUE TITLE
When a instagram reel or video have thumbnail it only shows the picture/thumbnail not the video

### ISSUE THREAD

**Issue by kpopdev** [Wikidepia/InstaFix#87]
for example this one : https://www.ddinstagram.com/p/C5Q9ERVuosb/
and this one https://www.ddinstagram.com/p/C2SPG5QOY-c/

**Comment by xxiiqq** [comment]
Same problem here :(

**Comment by Wikidepia** [comment]
You can read my explanation here: https://github.com/Wikidepia/InstaFix/issues/67
