### ISSUE TITLE
Unicode Replacement Character (�) Appears When Preview Text is Sliced at an Unlucky Index

### ISSUE THREAD

**Issue by TheV360** [Wikidepia/InstaFix#90]
## Summary

This post I saw in the wild ( https://www.instagram.com/reel/C5OXS6JL7Ii/ ) has a smart quote (U+2019) placed perfectly to be sliced in half by [this string slicing](https://github.com/Wikidepia/InstaFix/blob/333bfae99a50c10fe295ee0cba76fc75366efb56/handlers/embed.go#L116) because it operates on bytes instead of characters. This will happen more frequently in more posts as Apple's software keyboard has recently chosen to start using these Unicode characters for quotation marks and apostrophes.

This results in invalid characters, as seen here:

![](https://github.com/Wikidepia/InstaFix/assets/25177071/b38c7675-ae69-4c70-95a0-d0b92a4d2bef)

## Expected output, as a hex dump:

```
000000d0  49 20 6c 69 6b 65 20 74  68 65 69 72 20 63 6f 6d  |I like their com|
000000e0  70 61 6e 79 2c 20 49 e2  80 99 6d 20 6e 6f 74 20  |pany, I...m not |
000000f0  73 61 79 69 6e 67 20 69  74 2e 2e 2e              |saying it...|
```

## Actual output, as a hex dump:

This is directly copied from [a Go Playground sketch](https://go.dev/play/p/s689tdWJqvR) of what's happening in the `embed.go` code. Browsers do some additional processing that converts invalid characters into the replacement character, so `e2` becomes `ef bf bd` when seen in the browser.

```
000000d0  49 20 6c 69 6b 65 20 74  68 65 69 72 20 63 6f 6d  |I like their com|
000000e0  70 61 6e 79 2c 20 49 e2  80 99 6d 20 6e 6f 74 20  |pany, I...m not |
000000f0  73 61 79 69 6e 67 20 69  74 e2 2e 2e 2e           |saying it....|
```

## Solution:

Go probably has some helper functions to step through a string character by character rather than byte by byte. You could check the byte offset of each character and slice when there isn't enough space remaining to fit a `"...\000"` at the end. (I don't know if Go has null terminators actually. Ignore the `\000` if it doesn't.)

**Comment by Wikidepia** [comment]
Hello, this should be fixed now. Please let me know if the error still showing up
