### ISSUE TITLE
Reels do not embed, but can be embedded with simple url fix

### ISSUE THREAD

**Issue by ForgotTheColon** [Wikidepia/InstaFix#93]
Ex: I just shared https://www.ddinstagram.com/reel/C71eninSbNj/
This does not embed, however
https://www.ddinstagram.com/p/C71eninSbNj/ does.
It's not too hard as a user to fix, but it's be nice to fix on your end.

**Comment by ForgotTheColon** [comment]
Honestly this issue didn't seem all too consistent but yeah, right now dd Instagram hasn't been working for me

**Comment by Wikidepia** [comment]
This should work now, sometimes Discord/Telegram cache the old version and you need to change the url. Please reopen if InstaFix always failed to embed
