### ISSUE TITLE
"Post Might Not Be Available" for every post on specific public account

### ISSUE THREAD

**Issue by nguyentvan7** [Wikidepia/InstaFix#94]
https://www.ddinstagram.com/p/C75ipYLRd7r/?igsh=amdnaHhnM2VoZ3Y5
https://www.ddinstagram.com/p/C7ppee_sDKs/?igsh=cnlmNnpqNnpjN2c1
https://www.ddinstagram.com/p/C7etMDdRKaR/?igsh=MTBrcWlqZzF0dTExeg==

All of these posts are from the same public account, but none of the embeds will load. At the same time, embeds for other accounts will load instantly and work as expected. It seems to be specific to this account and has been a persistent issue for at least a month.

**Comment by Wikidepia** [comment]
Hello, InstaFix scrape a post information from the embed and the user ytyutiktv has disabled the embed functionality for their account. So it will always shows "Post Might Not Be Available" for that account. 

You can check it from this URL: https://www.instagram.com/p/C75ipYLRd7r/embed/captioned
