### ISSUE TITLE
InstaFix not working (14-Jun-2024)

### ISSUE THREAD

**Issue by Wikidepia** [Wikidepia/InstaFix#96]

**Comment by allanf181** [comment]
They've blocked company IPs, so when the request isn't made from a home IP it redirects to the login screen.

**Comment by NicoTheCinderace** [comment]
Yeah, it's completely broken.

**Comment by Wikidepia** [comment]
I am currently testing remote scraping from my LTE dongle, which should hopefully fix some embeds for the next 1-2 hours. I am also checking how much bandwidth it uses as my LTE is not unlimited...

**Comment by barraIhsan** [comment]
> They've blocked company IPs, so when the request isn't made from a home IP it redirects to the login screen.

sorry if this is a stupid question, but yt-dlp still works fine? or they just block ddinstagram.com to request?

**Comment by Wikidepia** [comment]
> > They've blocked company IPs, so when the request isn't made from a home IP it redirects to the login screen.
> 
> sorry if this is a stupid question, but yt-dlp still works fine? or they just block ddinstagram.com to request?

It will works fine if you only try to download a small number of posts. It became a problem when you have 5 or more posts every second

**Comment by styledliving** [comment]
> > > They've blocked company IPs, so when the request isn't made from a home IP it redirects to the login screen.
> 
> > 
> 
> > sorry if this is a stupid question, but yt-dlp still works fine? or they just block ddinstagram.com to request?
> 
> 
> 
> It will works fine if you only try to download a small number of posts. It became a problem when you have 5 or more posts every second

lemme know when you're ready to start a premium service. 👀

**Comment by MrTalon63** [comment]
> I am currently testing remote scraping from my LTE dongle, which should hopefully fix some embeds for the next 1-2 hours. I am also checking how much bandwidth it uses as my LTE is not unlimited...
> 
> upd: my dongle just died, please wait for another 2-3 days lol

Hi!
I have setup InstaFix at home with great results. It is available at fxxinstagram.com (It does not support all prefixes). If you need help hosting scrappers with residential IP addresses, I'm more than happy to help!

**Comment by barraIhsan** [comment]
update: the services is now up again!

**Comment by Wikidepia** [comment]
Yeap, I am currently testing with my phone as the LTE dongle. Seems to work fine hopefully my stuff will arrive tomorrow

**Comment by SaeidB** [comment]
Hello , I've found an easy solution for this issue, how can i contact author?

**Comment by Wikidepia** [comment]
> Hello , I've found an easy solution for this issue, how can i contact author?

Hello you can contact me at me@akmal.dev. It would be nice to have more way to scrape, thank you

**Comment by Wikidepia** [comment]
Seems to be stable enough after running for 3 days, I will close this issue
