### ISSUE TITLE
Format change

### ISSUE THREAD

**Issue by sallyFoster** [Wikidepia/InstaFix#97]
On Discord the format of embed instagrams changed and I hate it

**Comment by fadster** [comment]
What do you mean by format? From what I can tell, they're totally broken now. They just show a login message.

**Comment by sallyFoster** [comment]
@fadster You are right now is totally broken. When I posted the issue it was just partially broken. It looked like this

![image](https://github.com/Wikidepia/InstaFix/assets/104597302/1280d627-8c67-474d-b191-9ca0d1e1067d)

**Comment by StarComrade** [comment]
It is broken indeed. Something must've happened on Instagram's API.

**Comment by kpopdev** [comment]
@Wikidepia the ddinstagram.com is down for 3 days.

**Comment by kpopdev** [comment]
@Wikidepia all posts says : Post might not be available

**Comment by NicoTheCinderace** [comment]
@Wikidepia Yeah, it's completely broken.

**Comment by mrsideshowjack** [comment]
Yeah not working via [podaboutlist/linkfix-for-discord](https://github.com/podaboutlist/linkfix-for-discord)

![image](https://github.com/Wikidepia/InstaFix/assets/9937136/9d19fd85-b461-40e0-8bbd-f66136c1321d)
