### ISSUE TITLE
How do the embeds for telegram work?

### ISSUE THREAD

**Issue by sallyFoster** [Wikidepia/InstaFix#98]
It mentions on the top that embeds for telegram also work, but it doesn't say how to make them work on Discord

**Comment by Wikidepia** [comment]
It should be the same, but currently the website is broken as IG blocked this app. I am trying to fix it right now

**Comment by sallyFoster** [comment]
@Wikidepia Once it is working, could you please add a telegram example in the documentation? That would help out a lot. Thanks for all your hard work!
